### ISSUE TITLE
Issue-yarnの導入とjson-serverの導入

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-collector#10]
Automated Review Comments
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in yarn.lock:
  - (8, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (107, 'Line exceeds 80 characters')
  - (119, 'Line exceeds 80 characters')
  - (123, 'Line exceeds 80 characters')
  - (127, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (143, 'Line exceeds 80 characters')
  - (147, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (159, 'Line exceeds 80 characters')
  - (163, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (173, 'Line exceeds 80 characters')
  - (179, 'Line exceeds 80 characters')
  - (185, 'Line exceeds 80 characters')
  - (197, 'Line exceeds 80 characters')
  - (208, 'Line exceeds 80 characters')
  - (212, 'Line exceeds 80 characters')
  - (216, 'Line exceeds 80 characters')
  - (220, 'Line exceeds 80 characters')
  - (224, 'Line exceeds 80 characters')
  - (228, 'Line exceeds 80 characters')
  - (232, 'Line exceeds 80 characters')
  - (239, 'Line exceeds 80 characters')
  - (245, 'Line exceeds 80 characters')
  - (253, 'Line exceeds 80 characters')
  - (259, 'Line exceeds 80 characters')
  - (263, 'Line exceeds 80 characters')
  - (269, 'Line exceeds 80 characters')
  - (275, 'Line exceeds 80 characters')
  - (281, 'Line exceeds 80 characters')
  - (285, 'Line exceeds 80 characters')
  - (289, 'Line exceeds 80 characters')
  - (293, 'Line exceeds 80 characters')
  - (297, 'Line exceeds 80 characters')
  - (301, 'Line exceeds 80 characters')
  - (305, 'Line exceeds 80 characters')
  - (311, 'Line exceeds 80 characters')
  - (315, 'Line exceeds 80 characters')
  - (321, 'Line exceeds 80 characters')
  - (325, 'Line exceeds 80 characters')
  - (329, 'Line exceeds 80 characters')
  - (336, 'Line exceeds 80 characters')
  - (340, 'Line exceeds 80 characters')
  - (344, 'Line exceeds 80 characters')
  - (348, 'Line exceeds 80 characters')
  - (360, 'Line exceeds 80 characters')
  - (367, 'Line exceeds 80 characters')
  - (402, 'Line exceeds 80 characters')
  - (406, 'Line exceeds 80 characters')
  - (410, 'Line exceeds 80 characters')
  - (414, 'Line exceeds 80 characters')
  - (418, 'Line exceeds 80 characters')
  - (422, 'Line exceeds 80 characters')
  - (434, 'Line exceeds 80 characters')
  - (440, 'Line exceeds 80 characters')
  - (444, 'Line exceeds 80 characters')
  - (452, 'Line exceeds 80 characters')
  - (456, 'Line exceeds 80 characters')
  - (460, 'Line exceeds 80 characters')
  - (464, 'Line exceeds 80 characters')
  - (468, 'Line exceeds 80 characters')
  - (474, 'Line exceeds 80 characters')
  - (480, 'Line exceeds 80 characters')
  - (496, 'Line exceeds 80 characters')
  - (500, 'Line exceeds 80 characters')
  - (504, 'Line exceeds 80 characters')
  - (511, 'Line exceeds 80 characters')
  - (515, 'Line exceeds 80 characters')
  - (524, 'Line exceeds 80 characters')
  - (528, 'Line exceeds 80 characters')
  - (537, 'Line exceeds 80 characters')
  - (545, 'Line exceeds 80 characters')
  - (549, 'Line exceeds 80 characters')
  - (553, 'Line exceeds 80 characters')
  - (557, 'Line exceeds 80 characters')
  - (561, 'Line exceeds 80 characters')
  - (565, 'Line exceeds 80 characters')
  - (569, 'Line exceeds 80 characters')
  - (573, 'Line exceeds 80 characters')
  - (579, 'Line exceeds 80 characters')
  - (583, 'Line exceeds 80 characters')
  - (590, 'Line exceeds 80 characters')
  - (594, 'Line exceeds 80 characters')
  - (598, 'Line exceeds 80 characters')
  - (604, 'Line exceeds 80 characters')
  - (608, 'Line exceeds 80 characters')
  - (612, 'Line exceeds 80 characters')
  - (616, 'Line exceeds 80 characters')
  - (620, 'Line exceeds 80 characters')
  - (624, 'Line exceeds 80 characters')
  - (628, 'Line exceeds 80 characters')
  - (632, 'Line exceeds 80 characters')
  - (636, 'Line exceeds 80 characters')
  - (640, 'Line exceeds 80 characters')
  - (644, 'Line exceeds 80 characters')
  - (650, 'Line exceeds 80 characters')
  - (654, 'Line exceeds 80 characters')
  - (658, 'Line exceeds 80 characters')
  - (685, 'Line exceeds 80 characters')
  - (689, 'Line exceeds 80 characters')
  - (698, 'Line exceeds 80 characters')
  - (704, 'Line exceeds 80 characters')
  - (710, 'Line exceeds 80 characters')
  - (717, 'Line exceeds 80 characters')
  - (721, 'Line exceeds 80 characters')
  - (725, 'Line exceeds 80 characters')
  - (735, 'Line exceeds 80 characters')
  - (739, 'Line exceeds 80 characters')
  - (746, 'Line exceeds 80 characters')
  - (752, 'Line exceeds 80 characters')
  - (756, 'Line exceeds 80 characters')
  - (762, 'Line exceeds 80 characters')
  - (766, 'Line exceeds 80 characters')
  - (775, 'Line exceeds 80 characters')
  - (779, 'Line exceeds 80 characters')
  - (783, 'Line exceeds 80 characters')
  - (787, 'Line exceeds 80 characters')
  - (793, 'Line exceeds 80 characters')
  - (797, 'Line exceeds 80 characters')
  - (801, 'Line exceeds 80 characters')
  - (805, 'Line exceeds 80 characters')
  - (815, 'Line exceeds 80 characters')
  - (819, 'Line exceeds 80 characters')
  - (823, 'Line exceeds 80 characters')
  - (827, 'Line exceeds 80 characters')
  - (833, 'Line exceeds 80 characters')
  - (837, 'Line exceeds 80 characters')
  - (841, 'Line exceeds 80 characters')
  - (845, 'Line exceeds 80 characters')
  - (851, 'Line exceeds 80 characters')
  - (855, 'Line exceeds 80 characters')
  - (863, 'Line exceeds 80 characters')
  - (867, 'Line exceeds 80 characters')
  - (873, 'Line exceeds 80 characters')
  - (879, 'Line exceeds 80 characters')
  - (883, 'Line exceeds 80 characters')
  - (892, 'Line exceeds 80 characters')
  - (896, 'Line exceeds 80 characters')
  - (900, 'Line exceeds 80 characters')
  - (904, 'Line exceeds 80 characters')
  - (908, 'Line exceeds 80 characters')
  - (912, 'Line exceeds 80 characters')
  - (918, 'Line exceeds 80 characters')
  - (922, 'Line exceeds 80 characters')
  - (926, 'Line exceeds 80 characters')
  - (930, 'Line exceeds 80 characters')
  - (934, 'Line exceeds 80 characters')
  - (938, 'Line exceeds 80 characters')
  - (945, 'Line exceeds 80 characters')
  - (949, 'Line exceeds 80 characters')
  - (953, 'Line exceeds 80 characters')
  - (957, 'Line exceeds 80 characters')
  - (961, 'Line exceeds 80 characters')
  - (970, 'Line exceeds 80 characters')
  - (979, 'Line exceeds 80 characters')
  - (986, 'Line exceeds 80 characters')
  - (992, 'Line exceeds 80 characters')
  - (1019, 'Line exceeds 80 characters')
  - (1023, 'Line exceeds 80 characters')
  - (1027, 'Line exceeds 80 characters')
  - (1031, 'Line exceeds 80 characters')
  - (1037, 'Line exceeds 80 characters')
  - (1041, 'Line exceeds 80 characters')
  - (1059, 'Line exceeds 80 characters')
  - (1068, 'Line exceeds 80 characters')
  - (1072, 'Line exceeds 80 characters')
  - (1076, 'Line exceeds 80 characters')
  - (1080, 'Line exceeds 80 characters')
  - (1084, 'Line exceeds 80 characters')
  - (1090, 'Line exceeds 80 characters')
  - (1094, 'Line exceeds 80 characters')
  - (1098, 'Line exceeds 80 characters')
  - (1104, 'Line exceeds 80 characters')
  - (1118, 'Line exceeds 80 characters')
  - (1122, 'Line exceeds 80 characters')
  - (1126, 'Line exceeds 80 characters')
  - (1132, 'Line exceeds 80 characters')
  - (1140, 'Line exceeds 80 characters')
  - (1147, 'Line exceeds 80 characters')
  - (1151, 'Line exceeds 80 characters')
  - (1157, 'Line exceeds 80 characters')
  - (1163, 'Line exceeds 80 characters')
  - (1167, 'Line exceeds 80 characters')
  - (1171, 'Line exceeds 80 characters')
  - (1177, 'Line exceeds 80 characters')
  - (1183, 'Line exceeds 80 characters')
  - (1187, 'Line exceeds 80 characters')
  - (1193, 'Line exceeds 80 characters')
  - (1199, 'Line exceeds 80 characters')
  - (1203, 'Line exceeds 80 characters')
  - (1210, 'Line exceeds 80 characters')
  - (1216, 'Line exceeds 80 characters')
  - (1220, 'Line exceeds 80 characters')
  - (1224, 'Line exceeds 80 characters')
  - (1238, 'Line exceeds 80 characters')
  - (1244, 'Line exceeds 80 characters')
  - (1248, 'Line exceeds 80 characters')
  - (1252, 'Line exceeds 80 characters')
  - (1256, 'Line exceeds 80 characters')
  - (1264, 'Line exceeds 80 characters')
  - (1268, 'Line exceeds 80 characters')
  - (1274, 'Line exceeds 80 characters')
  - (1280, 'Line exceeds 80 characters')
  - (1287, 'Line exceeds 80 characters')
  - (1295, 'Line exceeds 80 characters')
  - (1299, 'Line exceeds 80 characters')
  - (1303, 'Line exceeds 80 characters')
  - (1307, 'Line exceeds 80 characters')
  - (1313, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
