### ISSUE TITLE
Issue-Mockサーバーの中身を登録

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-collector#18]
Automated Review Comments
Issues in mock/mock-server.json:
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (223, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (231, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (250, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (263, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (318, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (322, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (330, 'Hardcoded string found')
  - (331, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (338, 'Hardcoded string found')
  - (339, 'Hardcoded string found')
  - (342, 'Hardcoded string found')
  - (343, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (362, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (375, 'Hardcoded string found')
  - (378, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (390, 'Hardcoded string found')
  - (391, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (399, 'Hardcoded string found')
  - (402, 'Hardcoded string found')
  - (403, 'Hardcoded string found')
  - (406, 'Hardcoded string found')
  - (407, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (414, 'Hardcoded string found')
  - (415, 'Hardcoded string found')
  - (418, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (422, 'Hardcoded string found')
  - (423, 'Hardcoded string found')
  - (426, 'Hardcoded string found')
  - (427, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
  - (431, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (435, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (442, 'Hardcoded string found')
  - (443, 'Hardcoded string found')
  - (446, 'Hardcoded string found')
  - (447, 'Hardcoded string found')
  - (450, 'Hardcoded string found')
  - (451, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (455, 'Hardcoded string found')
  - (458, 'Hardcoded string found')
  - (459, 'Hardcoded string found')
  - (462, 'Hardcoded string found')
  - (464, 'Hardcoded string found')
  - (465, 'Hardcoded string found')
  - (466, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (480, 'Hardcoded string found')
  - (492, 'Hardcoded string found')
  - (493, 'Hardcoded string found')
  - (494, 'Hardcoded string found')
  - (506, 'Hardcoded string found')
  - (507, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (520, 'Hardcoded string found')
  - (521, 'Hardcoded string found')
  - (522, 'Hardcoded string found')
  - (534, 'Hardcoded string found')
  - (535, 'Hardcoded string found')
  - (536, 'Hardcoded string found')
  - (548, 'Hardcoded string found')
  - (549, 'Hardcoded string found')
  - (550, 'Hardcoded string found')
  - (562, 'Hardcoded string found')
  - (563, 'Hardcoded string found')
  - (564, 'Hardcoded string found')
  - (576, 'Hardcoded string found')
  - (577, 'Hardcoded string found')
  - (578, 'Hardcoded string found')
  - (590, 'Hardcoded string found')
  - (591, 'Hardcoded string found')
  - (592, 'Hardcoded string found')
  - (604, 'Hardcoded string found')
  - (605, 'Hardcoded string found')
  - (606, 'Hardcoded string found')
  - (618, 'Hardcoded string found')
  - (619, 'Hardcoded string found')
  - (620, 'Hardcoded string found')
  - (632, 'Hardcoded string found')
  - (633, 'Hardcoded string found')
  - (634, 'Hardcoded string found')
  - (646, 'Hardcoded string found')
  - (647, 'Hardcoded string found')
  - (648, 'Hardcoded string found')
  - (660, 'Hardcoded string found')
  - (661, 'Hardcoded string found')
  - (662, 'Hardcoded string found')
  - (674, 'Hardcoded string found')
  - (675, 'Hardcoded string found')
  - (676, 'Hardcoded string found')
  - (688, 'Hardcoded string found')
  - (689, 'Hardcoded string found')
  - (690, 'Hardcoded string found')
  - (702, 'Hardcoded string found')
  - (703, 'Hardcoded string found')
  - (704, 'Hardcoded string found')
  - (716, 'Hardcoded string found')
  - (717, 'Hardcoded string found')
  - (718, 'Hardcoded string found')
  - (730, 'Hardcoded string found')
  - (731, 'Hardcoded string found')
  - (732, 'Hardcoded string found')
  - (744, 'Hardcoded string found')
  - (745, 'Hardcoded string found')
  - (746, 'Hardcoded string found')
  - (758, 'Hardcoded string found')
  - (759, 'Hardcoded string found')
  - (760, 'Hardcoded string found')
  - (772, 'Hardcoded string found')
  - (773, 'Hardcoded string found')
  - (774, 'Hardcoded string found')
  - (786, 'Hardcoded string found')
  - (787, 'Hardcoded string found')
  - (788, 'Hardcoded string found')
  - (800, 'Hardcoded string found')
  - (801, 'Hardcoded string found')
  - (802, 'Hardcoded string found')
  - (814, 'Hardcoded string found')
  - (815, 'Hardcoded string found')
  - (816, 'Hardcoded string found')
  - (828, 'Hardcoded string found')
  - (829, 'Hardcoded string found')
  - (830, 'Hardcoded string found')
  - (842, 'Hardcoded string found')
  - (843, 'Hardcoded string found')
  - (844, 'Hardcoded string found')
  - (856, 'Hardcoded string found')
  - (857, 'Hardcoded string found')
  - (858, 'Hardcoded string found')
  - (870, 'Hardcoded string found')
  - (871, 'Hardcoded string found')
  - (872, 'Hardcoded string found')
  - (884, 'Hardcoded string found')
  - (885, 'Hardcoded string found')
  - (886, 'Hardcoded string found')
  - (898, 'Hardcoded string found')
  - (899, 'Hardcoded string found')
  - (900, 'Hardcoded string found')
  - (912, 'Hardcoded string found')
  - (913, 'Hardcoded string found')
  - (914, 'Hardcoded string found')
  - (926, 'Hardcoded string found')
  - (927, 'Hardcoded string found')
  - (928, 'Hardcoded string found')
  - (940, 'Hardcoded string found')
  - (941, 'Hardcoded string found')
  - (942, 'Hardcoded string found')
  - (954, 'Hardcoded string found')
  - (955, 'Hardcoded string found')
  - (956, 'Hardcoded string found')
  - (968, 'Hardcoded string found')
  - (969, 'Hardcoded string found')
  - (970, 'Hardcoded string found')
  - (982, 'Hardcoded string found')
  - (983, 'Hardcoded string found')
  - (984, 'Hardcoded string found')
  - (996, 'Hardcoded string found')
  - (997, 'Hardcoded string found')
  - (998, 'Hardcoded string found')
  - (1010, 'Hardcoded string found')
  - (1011, 'Hardcoded string found')
  - (1012, 'Hardcoded string found')
  - (1024, 'Hardcoded string found')
  - (1025, 'Hardcoded string found')
  - (1026, 'Hardcoded string found')
  - (1038, 'Hardcoded string found')
  - (1039, 'Hardcoded string found')
  - (1040, 'Hardcoded string found')
  - (1052, 'Hardcoded string found')
  - (1053, 'Hardcoded string found')
  - (1054, 'Hardcoded string found')
  - (1066, 'Hardcoded string found')
  - (1067, 'Hardcoded string found')
  - (1068, 'Hardcoded string found')
  - (1080, 'Hardcoded string found')
  - (1081, 'Hardcoded string found')
  - (1082, 'Hardcoded string found')
  - (1094, 'Hardcoded string found')
  - (1095, 'Hardcoded string found')
  - (1096, 'Hardcoded string found')
  - (1108, 'Hardcoded string found')
  - (1109, 'Hardcoded string found')
  - (1110, 'Hardcoded string found')
  - (1122, 'Hardcoded string found')
  - (1123, 'Hardcoded string found')
  - (1124, 'Hardcoded string found')
  - (1136, 'Hardcoded string found')
  - (1137, 'Hardcoded string found')
  - (1138, 'Hardcoded string found')
  - (1150, 'Hardcoded string found')
  - (1151, 'Hardcoded string found')
  - (1152, 'Hardcoded string found')
  - (1164, 'Hardcoded string found')
  - (1165, 'Hardcoded string found')
  - (1166, 'Hardcoded string found')
  - (1178, 'Hardcoded string found')
  - (1179, 'Hardcoded string found')
  - (1180, 'Hardcoded string found')
  - (1192, 'Hardcoded string found')
  - (1193, 'Hardcoded string found')
  - (1194, 'Hardcoded string found')
  - (1206, 'Hardcoded string found')
  - (1207, 'Hardcoded string found')
  - (1208, 'Hardcoded string found')
  - (1220, 'Hardcoded string found')
  - (1221, 'Hardcoded string found')
  - (1222, 'Hardcoded string found')
  - (1234, 'Hardcoded string found')
  - (1235, 'Hardcoded string found')
  - (1236, 'Hardcoded string found')
  - (1248, 'Hardcoded string found')
  - (1249, 'Hardcoded string found')
  - (1250, 'Hardcoded string found')
  - (1262, 'Hardcoded string found')
  - (1263, 'Hardcoded string found')
  - (1264, 'Hardcoded string found')
  - (1276, 'Hardcoded string found')
  - (1277, 'Hardcoded string found')
  - (1278, 'Hardcoded string found')
  - (1290, 'Hardcoded string found')
  - (1291, 'Hardcoded string found')
  - (1292, 'Hardcoded string found')
  - (1304, 'Hardcoded string found')
  - (1305, 'Hardcoded string found')
  - (1306, 'Hardcoded string found')
  - (1318, 'Hardcoded string found')
  - (1319, 'Hardcoded string found')
  - (1320, 'Hardcoded string found')
  - (1332, 'Hardcoded string found')
  - (1333, 'Hardcoded string found')
  - (1334, 'Hardcoded string found')
  - (1346, 'Hardcoded string found')
  - (1347, 'Hardcoded string found')
  - (1348, 'Hardcoded string found')
  - (1360, 'Hardcoded string found')
  - (1361, 'Hardcoded string found')
  - (1362, 'Hardcoded string found')
  - (1374, 'Hardcoded string found')
  - (1375, 'Hardcoded string found')
  - (1376, 'Hardcoded string found')
  - (1388, 'Hardcoded string found')
  - (1389, 'Hardcoded string found')
  - (1390, 'Hardcoded string found')
  - (1402, 'Hardcoded string found')
  - (1403, 'Hardcoded string found')
  - (1404, 'Hardcoded string found')
  - (1416, 'Hardcoded string found')
  - (1417, 'Hardcoded string found')
  - (1418, 'Hardcoded string found')
  - (1430, 'Hardcoded string found')
  - (1431, 'Hardcoded string found')
  - (1432, 'Hardcoded string found')
  - (1444, 'Hardcoded string found')
  - (1445, 'Hardcoded string found')
  - (1446, 'Hardcoded string found')
  - (1458, 'Hardcoded string found')
  - (1459, 'Hardcoded string found')
  - (1460, 'Hardcoded string found')
  - (1472, 'Hardcoded string found')
  - (1473, 'Hardcoded string found')
  - (1474, 'Hardcoded string found')
  - (1486, 'Hardcoded string found')
  - (1487, 'Hardcoded string found')
  - (1488, 'Hardcoded string found')
  - (1500, 'Hardcoded string found')
  - (1501, 'Hardcoded string found')
  - (1502, 'Hardcoded string found')
  - (1514, 'Hardcoded string found')
  - (1515, 'Hardcoded string found')
  - (1516, 'Hardcoded string found')
  - (1528, 'Hardcoded string found')
  - (1529, 'Hardcoded string found')
  - (1530, 'Hardcoded string found')
  - (1542, 'Hardcoded string found')
  - (1543, 'Hardcoded string found')
  - (1544, 'Hardcoded string found')
  - (1556, 'Hardcoded string found')
  - (1557, 'Hardcoded string found')
  - (1558, 'Hardcoded string found')
  - (1570, 'Hardcoded string found')
  - (1571, 'Hardcoded string found')
  - (1572, 'Hardcoded string found')
  - (1584, 'Hardcoded string found')
  - (1585, 'Hardcoded string found')
  - (1586, 'Hardcoded string found')
  - (1598, 'Hardcoded string found')
  - (1599, 'Hardcoded string found')
  - (1600, 'Hardcoded string found')
  - (1612, 'Hardcoded string found')
  - (1613, 'Hardcoded string found')
  - (1614, 'Hardcoded string found')
  - (1626, 'Hardcoded string found')
  - (1627, 'Hardcoded string found')
  - (1628, 'Hardcoded string found')
  - (1640, 'Hardcoded string found')
  - (1641, 'Hardcoded string found')
  - (1642, 'Hardcoded string found')
  - (1654, 'Hardcoded string found')
  - (1655, 'Hardcoded string found')
  - (1656, 'Hardcoded string found')
  - (1668, 'Hardcoded string found')
  - (1669, 'Hardcoded string found')
  - (1670, 'Hardcoded string found')
  - (1682, 'Hardcoded string found')
  - (1683, 'Hardcoded string found')
  - (1684, 'Hardcoded string found')
  - (1696, 'Hardcoded string found')
  - (1697, 'Hardcoded string found')
  - (1698, 'Hardcoded string found')
  - (1710, 'Hardcoded string found')
  - (1711, 'Hardcoded string found')
  - (1712, 'Hardcoded string found')
  - (1724, 'Hardcoded string found')
  - (1725, 'Hardcoded string found')
  - (1726, 'Hardcoded string found')
  - (1738, 'Hardcoded string found')
  - (1739, 'Hardcoded string found')
  - (1740, 'Hardcoded string found')
  - (1752, 'Hardcoded string found')
  - (1753, 'Hardcoded string found')
  - (1754, 'Hardcoded string found')
  - (1766, 'Hardcoded string found')
  - (1767, 'Hardcoded string found')
  - (1768, 'Hardcoded string found')
  - (1780, 'Hardcoded string found')
  - (1781, 'Hardcoded string found')
  - (1782, 'Hardcoded string found')
  - (1794, 'Hardcoded string found')
  - (1795, 'Hardcoded string found')
  - (1796, 'Hardcoded string found')
  - (1808, 'Hardcoded string found')
  - (1809, 'Hardcoded string found')
  - (1810, 'Hardcoded string found')
  - (1822, 'Hardcoded string found')
  - (1823, 'Hardcoded string found')
  - (1824, 'Hardcoded string found')
  - (1836, 'Hardcoded string found')
  - (1837, 'Hardcoded string found')
  - (1838, 'Hardcoded string found')
  - (1850, 'Hardcoded string found')
  - (1851, 'Hardcoded string found')
  - (1852, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
