### ISSUE TITLE
Issue-initial commit

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-collector#2]
Automated Review Comments
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
