### ISSUE TITLE
Issue-Mockの/assetsのbrand部分をidを使うように修正

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-collector#20]
Automated Review Comments
Issues in mock/mock-server.json:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
