### ISSUE TITLE
Issue-Mockサーバーのレスポンスの修正

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-collector#24]
Automated Review Comments
Issues in mock/mock-server.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (28, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
