### ISSUE TITLE
Issue-ionicの導入とディレクトリ構造のionic対応

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-collector#26]
Automated Review Comments
Issues in .gitignore:
  - (31, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
Issues in ionic.config.json:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
Issues in src/app/app.component.ts:
  - (20, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in src/app/app.html:
  - (2, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
Issues in src/index.html:
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
Issues in src/manifest.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in src/pages/home/home.html:
  - (5, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
Issues in src/pages/list/list.html:
  - (5, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in src/pages/list/list.ts:
  - (15, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
Issues in src/service-worker.js:
  - (8, 'Hardcoded string found')
Issues in src/theme/variables.scss:
  - (35, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
Issues in tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
Issues in tslint.json:
  - (3, 'Hardcoded string found')
  - (9, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
